openapi: 3.1.0
info:
  title: Humetime Excel Action (Google Sheets)
  version: "1.0.0"
servers:
  - url: https://humetime-server.onrender.com
paths:
  /append:
    post:
      operationId: appendRow
      summary: Ajouter une ligne de distribution
      parameters:
        - name: x-api-key
          in: header
          required: false
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nb_patients, duree_distribution_min, repas, nb_personnes]
              properties:
                horodatage: { type: string }
                nb_patients: { type: integer, minimum: 0 }
                duree_distribution_min: { type: integer, minimum: 0 }
                repas: { type: string }
                nb_personnes: { type: integer, minimum: 0 }
                notes_libres: { type: string, nullable: true }
                source_message: { type: string, nullable: true }
      responses:
        "200": { description: OK }
